### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [4]:
#1.1
numeriPrimi = []
for i in range(2,100):
    primo = True
    for n in range(2, i):
        if i%n == 0:
            primo = False
    if primo: numeriPrimi.append(i)
print(numeriPrimi)

numeriPrimiComp = [
    i for i in range(2, 100)
    if all(i % n != 0 for n in range(2, i))
]
print(numeriPrimiComp)

#1.2
potenze = [i**2 for i in range(1,10)]
print(potenze)


#1.3
sommaComulativa = []
for i in range(1, 11):
    somma = 0
    for n in range(1, i):
        somma = somma + n
    sommaComulativa.append(somma)

print(sommaComulativa)

sommaComulativaComp = [sum(n for n in range(1, i)) for i in range(1, 11)]

print(sommaComulativaComp)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]
[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [5]:
import numpy as np

a = np.array([n for n in range(1, 11)])
b = np.array([i for i in range(2,11)
     if all(i%n != 0 for n in range(2, i))])
print(a.size)
print(len(a))
print(a.dtype)
print(b)

10
10
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [6]:
import numpy as np
import random
a = np.array([random.randint(1, 10) for i in range(1,5)])
b = np.append(a, "substring")
c = np.flip(a)
print(a)
print(b)
print(c)
print(a/c)

[10  2  6  2]
['10' '2' '6' '2' 'substring']
[ 2  6  2 10]
[5.         0.33333333 3.         0.2       ]
