In [28]:
#ESERCIZIO 1

#1.1
numeriPrimi = []
for i in range(2,100):
    primo = True
    for n in range(2, i):
        if i%n == 0:
            primo = False
    if primo: numeriPrimi.append(i)
print(numeriPrimi)

numeriPrimiComp = [
    i for i in range(2, 100)
    if all(i % n != 0 for n in range(2, i))
]
print(numeriPrimiComp)

In [38]:
#1.2
potenze = [i**2 for i in range(1,10)]
print(potenze)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [54]:
#1.3
sommaComulativa = []
for i in range(1, 11):
    somma = 0
    for n in range(1, i):
        somma = somma + n
    sommaComulativa.append(somma)

print(sommaComulativa)

sommaComulativaComp = [sum(n for n in range(1, i)) for i in range(1, 11)]

print(sommaComulativaComp)

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]


In [68]:
#ESERCIZIO 2
import numpy as np
a = np.array([n for n in range(1, 11)])
b = np.array([i for i in range(2,11)
     if all(i%n != 0 for n in range(2, i))])
print(a.size)
print(len(a))
print(a.dtype)
print(b)

10
10
int64
[2 3 5 7]


In [89]:
#ESERCIZIO 3
import numpy as np
import random
a = np.array([random.randint(1, 10) for i in range(1,5)])
b = np.append(a, "substring")
c = np.flip(a)
print(a)
print(b)
print(c)
print(a/c)

[ 8 10  4  7]
['8' '10' '4' '7' 'substring']
[ 7  4 10  8]
[1.14285714 2.5        0.4        0.875     ]
